# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tg-course-state-704505749045"
    dynamodb_table = "tg_course_locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-2"
  }
}
